#!/usr/bin/env python3
"""Bundle markdown files into a single JS module for offline use."""

import json
from pathlib import Path

ROOT = Path(__file__).parent
CONTENT_DIR = ROOT / "content"
OUT = ROOT / "js" / "content-bundle.js"

CATALOG = [
    {
        "id": "logic",
        "title": "Логические задания L1",
        "subtitle": "10 тем · нейрофизиология через рассуждение",
        "file": "l1-logic-assignments-ru.md",
        "icon": "🧠",
    },
    {
        "id": "integrated",
        "title": "Интегрированные задания L1",
        "subtitle": "Pipeline · naive vs correct",
        "file": "l1-integrated-assignments-ru.md",
        "icon": "⚡",
    },
]


def main() -> None:
    docs = []
    for item in CATALOG:
        path = CONTENT_DIR / item["file"]
        if not path.exists():
            raise FileNotFoundError(path)
        docs.append({**item, "markdown": path.read_text(encoding="utf-8")})

    payload = json.dumps(docs, ensure_ascii=False)
    OUT.write_text(
        f"/* Auto-generated by build_content.py — do not edit */\n"
        f"window.NIMBUS_CONTENT = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB, {len(docs)} documents)")


if __name__ == "__main__":
    main()
